
exec-once = qs -c noctalia-shell
exec-once = . ~/.profile; /home/shiraneko/go/bin/Surge server --token $SURGE_TOKEN
exec-once = ~/.config/hypr/scripts/zen-bitwarden-float.sh
exec-once = /home/shiraneko/.local/bin/ABDownloadManager --background

# Set scrolling layout
exec-once = hyprctl keyword general:layout scrolling

# Slow app launch fix -- set systemd vars
exec-once = systemctl --user import-environment $(env | cut -d'=' -f1)
exec-once = dbus-update-activation-environment --systemd --all
