source = ~/.config/hypr/bindings/media.conf
source = ~/.config/hypr/bindings/clipboard.conf
source = ~/.config/hypr/bindings/tiling-v2.conf
source = ~/.config/hypr/bindings/utilities.conf

# Application bindings
bindd = SUPER, RETURN, Terminal, exec, kitty
bindd = SUPER SHIFT, RETURN, Browser, exec, zen-browser
bindd = SUPER, E, File manager, exec, nautilus
bindd = SUPER, B, Browser, exec, chromium
bindd = SUPER SHIFT ALT, B, Browser (private), exec, chromium --incognito
bindd = SUPER SHIFT, M, Music, exec, flatpak run com.spotify.Client
bindd = SUPER SHIFT, N, Editor, exec, zeditor
bindd = SUPER SHIFT, S, Open Surge TUI, exec, kitty --class org.float.surge -T Surge --hold -e sh -lc '. ~/.profile && /home/shiraneko/go/bin/Surge connect "$SURGE_HOST" --token "$SURGE_TOKEN"'
bindd = SUPER SHIFT, D, Open dotfiles, exec, zeditor ~/dotfiles
bindd = SUPER SHIFT, A, Anytype, exec, flatpak run io.anytype.anytype


# Add extra bindings
# bind = SUPER SHIFT, R, exec, alacritty -e ssh your-server

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu
