$ipc = qs -c noctalia-shell ipc

# Copy / Paste
bindd = SUPER, C, Universal copy, sendshortcut, CTRL, Insert,
bindd = SUPER, V, Universal paste, sendshortcut, SHIFT, Insert,
bindd = SUPER, X, Universal cut, sendshortcut, CTRL, X,
bindd = SUPER CTRL, V, Clipboard manager, exec, $ipc call plugin:clipper toggle
bindd = SUPER CTRL, C, Add to NoteCard, exec, $ipc call plugin:clipper addSelectionToNoteCard
bindd = SUPER SHIFT, V, Noctalia Clipboard, exec, $ipc call launcher clipboard
