$ipc = qs -c noctalia-shell ipc

# Laptop multimedia keys for volume and LCD brightness (with OSD)
bindeld = ,XF86AudioRaiseVolume, Volume up, exec, $ipc call volume increase
bindeld = ,XF86AudioLowerVolume, Volume down, exec, $ipc call volume decrease
bindeld = ,XF86AudioMute, Mute, exec, $ipc call volume muteOutput

# Requires playerctl
bindld = , XF86AudioNext, Next track, exec, $ipc call media next
bindld = , XF86AudioPause, Pause, exec, $ipc call media playPause
bindld = , XF86AudioPlay, Play, exec, $ipc call media playPause
bindld = , XF86AudioPrev, Previous track, exec, $ipc call media previous
