$ipc = qs -c noctalia-shell ipc

# Menus
bindd = SUPER, SPACE, Launch apps, exec, $ipc call launcher toggle
bindd = SUPER CTRL, E, Emoji picker, exec, $ipc call launcher emoji
bindd = SUPER, ESCAPE, System menu, exec, $ipc call sessionMenu toggle
bindd = SUPER SHIFT, Q, Lock and suspend, exec, $ipc call sessionMenu lockAndSuspend
bindd = SUPER, K, Show key bindings, exec, $ipc call plugin togglePanel keybind-cheatsheet
bindd = , XF86Calculator, Calculator, exec, gnome-calculator


# Notifications
bindd = SUPER, COMMA, Noctalia Settings, exec, $ipc call settings open

# Toggles
bindd = SUPER CTRL, N, Toggle nightlight, exec, $ipc call nightLight toggle
bindd = SUPER SHIFT, P, Toggle Noctalia Performance, exec, $ipc call powerProfile toggleNoctaliaPerformance
bindd = SUPER CTRL, P, Toggle Performance, exec, $ipc call powerProfile cycle

# Captures
bindd = , PRINT, Screenshot full screen, exec, $ipc call plugin:screenshot takeScreenshot output
bindd = ALT, PRINT, Screenshot a window, exec, $ipc call plugin:screenshot takeScreenshot window
bindd = CTRL, PRINT, Screenshot a region, exec, $ipc call plugin:screenshot takeScreenshot region
bindd = SUPER, PRINT, Screenrecording, exec, $ipc call plugin:screen-recorder toggle
# bindd = SUPER, PRINT, Color picker, exec, pkill hyprpicker || hyprpicker -a

# File sharing
bindd = SUPER CTRL, S, Share, exec, localsend

# Control panels
bindd = SUPER CTRL, T, Activity, exec, kitty --class org.float.btop -T BTOP -e btop

# Dictation
bindd = SUPER CTRL, X, Toggle dictation, exec, voxtype record toggle

# Zoom
bindd = SUPER CTRL, Z, Zoom in, exec, hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '.float + 1')
bindd = SUPER CTRL ALT, Z, Reset zoom, exec, hyprctl keyword cursor:zoom_factor 1

# Lock system
bindd = SUPER, L, Lock screen, exec, $ipc call sessionMenu lock
