#!/bin/bash
# Utility to run a command in a floating kitty terminal
# The app-id will start with "float-" to trigger the niri floating rule.

COMMAND="$1"
shift
ARGS="$@"

# If no command, just open a floating terminal
if [ -z "$COMMAND" ]; then
    exec kitty --class float-kitty
fi

# Run the command
exec kitty --class "float-$COMMAND" -e "$COMMAND" $ARGS
